use prism_drain::EnrichedTemplate;
use prism_profiler::SourceProfile;
use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Error, Debug)]
pub enum VrlGeneratorError {
    #[error("VRL compilation failed: {0}")]
    CompilationFailed(String),
    #[error("Dry-run failed: {0}")]
    DryRunFailed(String),
    #[error("LLM request failed: {0}")]
    LlmRequestFailed(String),
    #[error("Validation failed: {0}")]
    ValidationFailed(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VrlScript {
    pub content: String,
    pub class_uid: i64,
    pub category_uid: i64,
    pub type_uid: i64,
    pub field_count: usize,
    pub validation_passed: bool,
    pub warnings: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScoreReport {
    pub vrl_compile_passed: bool,
    pub dry_run_passed: bool,
    pub fixtures_total: usize,
    pub fixtures_passed: usize,
    pub field_accuracy: f64,
    pub ocsf_validation_passed: bool,
    pub unknown_paths: Vec<String>,
    pub overall_score: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GeneratorMode {
    Heuristic,
    FineTuned,
    Llm,
}

pub struct VrlGenerator {
    mode: GeneratorMode,
    llm_client: Option<LlmClient>,
    #[allow(dead_code)]
    fine_tuned_model_path: Option<String>,
}

#[derive(Clone)]
struct LlmClient {
    endpoint: String,
    model: String,
    client: reqwest::Client,
}

impl VrlGenerator {
    pub fn heuristic() -> Self {
        Self {
            mode: GeneratorMode::Heuristic,
            llm_client: None,
            fine_tuned_model_path: None,
        }
    }

    pub fn fine_tuned(model_path: String) -> Self {
        Self {
            mode: GeneratorMode::FineTuned,
            llm_client: None,
            fine_tuned_model_path: Some(model_path),
        }
    }

    pub fn llm(endpoint: String, model: String) -> Self {
        Self {
            mode: GeneratorMode::Llm,
            llm_client: Some(LlmClient {
                endpoint,
                model,
                client: reqwest::Client::new(),
            }),
            fine_tuned_model_path: None,
        }
    }

    pub async fn generate_from_template(&self, template: &EnrichedTemplate) -> Result<VrlScript, VrlGeneratorError> {
        self.generate_from_enriched_template(template).await
    }

    pub async fn generate_from_enriched_template(&self, template: &EnrichedTemplate) -> Result<VrlScript, VrlGeneratorError> {
        let mut profile = prism_profiler::profile(&template.samples)
            .await
            .unwrap_or_else(|_| prism_profiler::SourceProfile {
                sample_count: template.samples.len(),
                wire_format: "unknown".into(),
                wire_format_confidence: 0.0,
                decoder_chain: Vec::new(),
                source_family: "unknown".into(),
                source_family_confidence: 0.0,
                suggested_class_uid: Some(template.class_uid),
                source_hypotheses: Vec::new(),
                extracted_field_names: Vec::new(),
                stable_detector_terms: template.detector_terms.clone(),
                evidence: Vec::new(),
                warnings: Vec::new(),
                recommended_next_step: String::new(),
            });

        profile.suggested_class_uid = Some(template.class_uid);
        for dt in &template.detector_terms {
            if !profile.stable_detector_terms.contains(dt) {
                profile.stable_detector_terms.push(dt.clone());
            }
        }

        self.generate(&template.samples, &profile).await
    }

    pub async fn generate(&self, samples: &[String], profile: &SourceProfile) -> Result<VrlScript, VrlGeneratorError> {
        match self.mode {
            GeneratorMode::Heuristic => self.generate_heuristic(samples, profile),
            GeneratorMode::FineTuned => self.generate_fine_tuned(samples, profile),
            GeneratorMode::Llm => self.generate_llm(samples, profile).await,
        }
    }

    fn generate_heuristic(&self, _samples: &[String], profile: &SourceProfile) -> Result<VrlScript, VrlGeneratorError> {
        let class_uid = profile.suggested_class_uid.unwrap_or(4001);
        let mut lines = Vec::new();
        lines.push("# Generated by prism-vrl-generator heuristic-v1".to_string());
        lines.push(format!("# Class: {} ({})", class_name(class_uid), class_uid));
        lines.push("".to_string());

        // Decoder chain (strictly avoid parse_syslog to prevent pipeline stalls on varied formats)
        for decoder in &profile.decoder_chain {
            let dec = decoder.to_lowercase();
            if dec.contains("syslog") {
                continue;
            }
            if dec.contains("json") {
                lines.push(". = parse_json!(.message)".to_string());
            } else if dec.contains("cef") {
                lines.push(". = parse_cef!(.message)".to_string());
            } else if dec.contains("common_log") {
                lines.push(". = parse_common_log!(.message)".to_string());
            }
        }

        let mut extracted_ocsf_targets = std::collections::HashSet::new();

        // Field extractions from profile.extracted_field_names
        for (idx, source_field) in profile.extracted_field_names.iter().enumerate() {
            let ocsf_path = infer_ocsf_path(source_field);
            if !ocsf_path.is_empty() && !extracted_ocsf_targets.contains(&ocsf_path) {
                let var_name = format!("m_field_{}", idx);
                lines.push(format!(
                    "{}, err = parse_regex(string!(.message), r'(?i){}=(?P<val>[^\\s,\"]+)')\nif err == null {{\n  .{} = {}.val\n}}",
                    var_name, source_field, ocsf_path, var_name
                ));
                extracted_ocsf_targets.insert(ocsf_path);
            }
        }

        // Class-specific fallback extractions
        match class_uid {
            3001 => {
                if !extracted_ocsf_targets.contains("actor.user.name") {
                    lines.push("m_user, err = parse_regex(string!(.message), r'(?:user[ =]|for(?: invalid user)? )(?P<user>[^\\s,;\"]+)')\nif err == null {\n  .actor.user.name = m_user.user\n}".to_string());
                }
                if !extracted_ocsf_targets.contains("src_endpoint.ip") {
                    lines.push("m_ip, err = parse_regex(string!(.message), r'(?:from|rhost=)\\s*(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+)')\nif err == null {\n  .src_endpoint.ip = m_ip.ip\n}".to_string());
                }
                if !extracted_ocsf_targets.contains("src_endpoint.port") {
                    lines.push("m_port, err = parse_regex(string!(.message), r'port\\s+(?P<port>\\d+)')\nif err == null {\n  .src_endpoint.port = to_int(m_port.port) ?? null\n}".to_string());
                }
            }
            2004 => {
                if !extracted_ocsf_targets.contains("src_endpoint.ip") {
                    lines.push("m_ip, err = parse_regex(string!(.message), r'(?:\\{[A-Z]+\\}|SRC=)\\s*(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+)')\nif err == null {\n  .src_endpoint.ip = m_ip.ip\n}".to_string());
                }
                if !extracted_ocsf_targets.contains("dst_endpoint.ip") {
                    lines.push("m_dst, err = parse_regex(string!(.message), r'(?:->|DST=)\\s*(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+)')\nif err == null {\n  .dst_endpoint.ip = m_dst.ip\n}".to_string());
                }
            }
            4001 => {
                if !extracted_ocsf_targets.contains("src_endpoint.ip") {
                    lines.push("m_src, err = parse_regex(string!(.message), r'(?:SRC|srcip|src)=(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+)')\nif err == null {\n  .src_endpoint.ip = m_src.ip\n}".to_string());
                }
                if !extracted_ocsf_targets.contains("dst_endpoint.ip") {
                    lines.push("m_dst, err = parse_regex(string!(.message), r'(?:DST|dstip|dst)=(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+)')\nif err == null {\n  .dst_endpoint.ip = m_dst.ip\n}".to_string());
                }
                if !extracted_ocsf_targets.contains("connection_info.protocol_name") {
                    lines.push("m_proto, err = parse_regex(string!(.message), r'(?:PROTO|proto)=(?P<proto>\\w+)')\nif err == null {\n  .connection_info.protocol_name = m_proto.proto\n}".to_string());
                }
            }
            5001 => {
                if !extracted_ocsf_targets.contains("http.request.method") {
                    lines.push("m_method, err = parse_regex(string!(.message), r'(?P<method>GET|POST|PUT|DELETE|HEAD)')\nif err == null {\n  .http.request.method = m_method.method\n}".to_string());
                }
                if !extracted_ocsf_targets.contains("src_endpoint.ip") {
                    lines.push("m_ip, err = parse_regex(string!(.message), r'(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+)')\nif err == null {\n  .src_endpoint.ip = m_ip.ip\n}".to_string());
                }
                if !extracted_ocsf_targets.contains("url.url_string") {
                    lines.push("m_url, err = parse_regex(string!(.message), r'\"(?:GET|POST|PUT|DELETE|HEAD)\\s+(?P<url>[^\\s\"]+)')\nif err == null {\n  .url.url_string = m_url.url\n}".to_string());
                }
            }
            8001
                if !extracted_ocsf_targets.contains("file.name") => {
                    lines.push("m_file, err = parse_regex(string!(.message), r'(?P<file>[\\w\\-. ]+\\.(?:exe|dll|pdf|docx?|xlsx?))')\nif err == null {\n  .file.name = m_file.file\n}".to_string());
                }
            _ => {}
        }

        // Standard OCSF required metadata fields
        lines.push(format!(".class_uid = {}", class_uid));
        lines.push(format!(".category_uid = {}", category_uid_for_class(class_uid)));
        lines.push(format!(".type_uid = {}", type_uid_for_class(class_uid)));

        let content = lines.join("\n");
        validate_vrl(&content)?;

        Ok(VrlScript {
            content,
            class_uid,
            category_uid: category_uid_for_class(class_uid),
            type_uid: type_uid_for_class(class_uid),
            field_count: profile.extracted_field_names.len().max(extracted_ocsf_targets.len()),
            validation_passed: true,
            warnings: vec!["Generated by heuristic mode - review before deployment".to_string()],
        })
    }


    fn generate_fine_tuned(&self, samples: &[String], profile: &SourceProfile) -> Result<VrlScript, VrlGeneratorError> {
        // TODO: Implement fine-tuned model inference
        // For now, fall back to heuristic
        self.generate_heuristic(samples, profile)
    }

    async fn generate_llm(&self, samples: &[String], profile: &SourceProfile) -> Result<VrlScript, VrlGeneratorError> {
        let Some(client) = &self.llm_client else {
            return Err(VrlGeneratorError::LlmRequestFailed("No LLM client configured".into()));
        };

        let prompt = build_llm_prompt(samples, profile);
        let response = client.complete(prompt).await?;

        let vrl = extract_vrl_from_response(&response)?;
        validate_vrl(&vrl)?;

        Ok(VrlScript {
            content: vrl,
            class_uid: profile.suggested_class_uid.unwrap_or(4001),
            category_uid: profile.suggested_class_uid.map(category_uid_for_class).unwrap_or(4),
            type_uid: type_uid_for_class(profile.suggested_class_uid.unwrap_or(4001)),
            field_count: profile.extracted_field_names.len(),
            validation_passed: true,
            warnings: vec!["Generated by LLM - review before deployment".to_string()],
        })
    }

    pub async fn validate_and_score(&self, vrl: &str, samples: &[String], profile: &SourceProfile) -> Result<ScoreReport, VrlGeneratorError> {
        // Compile VRL
        compile_vrl(vrl)?;

        // Dry-run with samples
        let mut total_fields = 0;
        let mut matched_fields = 0;

        for sample in samples {
            let result = run_dry_run(vrl, sample)?;
            let fields = extract_fields(&result)?;
            total_fields += fields.len();
            for path in fields {
                if profile.extracted_field_names.iter().any(|f| path.contains(f)) {
                    matched_fields += 1;
                }
            }
        }

        let field_accuracy = if total_fields > 0 {
            matched_fields as f64 / total_fields as f64
        } else {
            0.0
        };

        Ok(ScoreReport {
            vrl_compile_passed: true,
            dry_run_passed: true,
            fixtures_total: samples.len(),
            fixtures_passed: samples.len(),
            field_accuracy,
            ocsf_validation_passed: true,
            unknown_paths: Vec::new(),
            overall_score: field_accuracy * 0.5 + 0.5,
        })
    }
}

impl LlmClient {
    async fn complete(&self, prompt: String) -> Result<String, VrlGeneratorError> {
        let req = serde_json::json!({
            "model": self.model,
            "prompt": prompt,
            "stream": false,
            "options": {
                "temperature": 0.1,
                "num_predict": 1024,
                "repeat_penalty": 1.1,
                "repeat_last_n": 64,
            }
        });

        let resp = self.client
            .post(format!("{}/api/generate", self.endpoint))
            .json(&req)
            .timeout(std::time::Duration::from_secs(60))
            .send()
            .await
            .map_err(|e| VrlGeneratorError::LlmRequestFailed(e.to_string()))?;

        if !resp.status().is_success() {
            return Err(VrlGeneratorError::LlmRequestFailed(format!("HTTP {}", resp.status())));
        }

        let data: serde_json::Value = resp.json().await.map_err(|e| VrlGeneratorError::LlmRequestFailed(e.to_string()))?;
        Ok(data["response"].as_str().unwrap_or("").to_string())
    }
}

fn extract_vrl_from_response(response: &str) -> Result<String, VrlGeneratorError> {
    // Extract VRL code from LLM response
    // Handles markdown code blocks and plain text
    let content = response.trim();
    
    // Try to extract from markdown code blocks first
    if let Some(start) = content.find("```") {
        let after_start = &content[start + 3..];
        if let Some(end) = after_start.find("```") {
            let code = &after_start[..end].trim();
            // Skip language identifier if present
            if let Some(newline_pos) = code.find('\n') {
                return Ok(code[newline_pos + 1..].trim().to_string());
            }
            return Ok(code.trim().to_string());
        }
    }
    
    // If no code blocks, return the whole response trimmed
    Ok(content.trim().to_string())
}

fn build_llm_prompt(samples: &[String], profile: &SourceProfile) -> String {
    let available_fields = profile.extracted_field_names.join(", ");

    format!(
        r#"You are an expert in Vector Remap Language (VRL) for OCSF mapping.

CRITICAL RULES:
1. Use `.field = value` for assignment (NOT `:=` or `=`)
2. Use `parse_regex!(string!(.message), r'pattern').capture` for extraction
3. Use `parse_syslog!(.message)` for syslog parsing
4. Use `parse_json!(.message)` for JSON parsing
5. String literals use double quotes: `"value"`
6. Regex patterns use raw strings: `r'pattern'`
7. Comments start with `#`
8. NO markdown formatting - return ONLY raw VRL code
9. Always set `.class_uid`, `.category_uid`, `.type_uid` as integers
10. Use `.src_endpoint.ip` and `.dst_endpoint.ip` for network events
11. For user fields: `.user.name = "value"`
12. For HTTP: `.http.request.method`, `.http.request.url`, `.http.response.status_code`
13. For files: `.file.name`, `.file.path`

OCSF Class UID: {} ({})
Category UID: {}
Type UID: {}

AVAILABLE SOURCE FIELDS: {}

EXAMPLE VRL:
{}

LOG SAMPLES:
{}

Generate VRL that extracts fields and maps to OCSF. Return ONLY the VRL code."#,
        profile.suggested_class_uid.unwrap_or(4001),
        class_name(profile.suggested_class_uid.unwrap_or(4001)),
        profile.suggested_class_uid.map(category_uid_for_class).unwrap_or(4),
        type_uid_for_class(profile.suggested_class_uid.unwrap_or(4001)),
        available_fields,
        example_vrl_for_class(profile.suggested_class_uid.unwrap_or(4001)),
        shown_samples(samples)
    )
}

fn validate_vrl(vrl: &str) -> Result<(), VrlGeneratorError> {
    // Basic validation
    if vrl.is_empty() {
        return Err(VrlGeneratorError::ValidationFailed("Empty VRL".into()));
    }
    if vrl.contains("```") || vrl.contains("```vrl") {
        return Err(VrlGeneratorError::ValidationFailed("Contains markdown formatting".into()));
    }
    if !vrl.contains(".class_uid =") {
        return Err(VrlGeneratorError::ValidationFailed("Missing .class_uid".into()));
    }
    if !vrl.contains(".category_uid =") {
        return Err(VrlGeneratorError::ValidationFailed("Missing .category_uid".into()));
    }
    if !vrl.contains(".type_uid =") {
        return Err(VrlGeneratorError::ValidationFailed("Missing .type_uid".into()));
    }
    if vrl.contains(":=") {
        return Err(VrlGeneratorError::ValidationFailed("Contains := assignment".into()));
    }
    compile_vrl(vrl)?;
    Ok(())
}

pub fn compile_vrl(vrl_str: &str) -> Result<(), VrlGeneratorError> {
    if vrl_str.trim().is_empty() {
        return Err(VrlGeneratorError::CompilationFailed("Empty VRL".into()));
    }
    let fns = vrl::stdlib::all();
    vrl::compiler::compile(vrl_str, &fns)
        .map_err(|e| VrlGeneratorError::CompilationFailed(format!("{:?}", e)))?;
    Ok(())
}

pub fn run_dry_run(vrl_str: &str, sample: &str) -> Result<serde_json::Value, VrlGeneratorError> {
    let fns = vrl::stdlib::all();
    let res = vrl::compiler::compile(vrl_str, &fns)
        .map_err(|e| VrlGeneratorError::CompilationFailed(format!("{:?}", e)))?;

    let mut map = std::collections::BTreeMap::new();
    map.insert("message".into(), vrl::value::Value::from(sample));
    let value = vrl::value::Value::Object(map);

    let mut target = vrl::compiler::TargetValue {
        value,
        metadata: vrl::value::Value::Object(std::collections::BTreeMap::new()),
        secrets: vrl::value::Secrets::new(),
    };

    let mut state = vrl::compiler::state::RuntimeState::default();
    let tz = vrl::compiler::TimeZone::default();
    let mut ctx = vrl::compiler::Context::new(&mut target, &mut state, &tz);

    res.program
        .resolve(&mut ctx)
        .map_err(|e| VrlGeneratorError::DryRunFailed(format!("{:?}", e)))?;

    serde_json::to_value(&target.value)
        .map_err(|e| VrlGeneratorError::DryRunFailed(e.to_string()))
}

pub fn extract_fields(result: &serde_json::Value) -> Result<Vec<String>, VrlGeneratorError> {
    let mut fields = Vec::new();
    collect_fields("", result, &mut fields);
    Ok(fields)
}

fn collect_fields(prefix: &str, val: &serde_json::Value, fields: &mut Vec<String>) {
    if let serde_json::Value::Object(map) = val {
        for (k, v) in map {
            let full = if prefix.is_empty() {
                k.clone()
            } else {
                format!("{}.{}", prefix, k)
            };
            fields.push(full.clone());
            collect_fields(&full, v, fields);
        }
    }
}

fn category_uid_for_class(class_uid: i64) -> i64 {
    match class_uid {
        4001 => 4,   // Network Activity
        3001 => 3,   // Authentication
        5001 => 5,   // Web Activity
        8001 => 8,   // File Activity
        2004 => 2,   // Detection Finding
        1001 => 1,   // Process Activity
        6001 => 6,   // DNS Activity
        _ => 4,
    }
}

fn type_uid_for_class(class_uid: i64) -> i64 {
    match class_uid {
        4001 => 400101,
        3001 => 300101,
        5001 => 500101,
        8001 => 800101,
        2004 => 200401,
        1001 => 100101,
        6001 => 600101,
        _ => 400101,
    }
}

fn class_name(class_uid: i64) -> &'static str {
    match class_uid {
        4001 => "Network Activity",
        3001 => "Authentication",
        5001 => "Web Activity",
        8001 => "File Activity",
        2004 => "Detection Finding",
        1001 => "Process Activity",
        6001 => "DNS Activity",
        _ => "Network Activity",
    }
}

fn example_vrl_for_class(class_uid: i64) -> String {
    match class_uid {
        4001 => r#".message = parse_syslog!(.message)
.ip = parse_regex!(string!(.message), r'(?P<ip>\d+\.\d+\.\d+\.\d+)').ip
.class_uid = 4001
.category_uid = 4
.type_uid = 400101
.src_endpoint.ip = .ip
.dst_endpoint.ip = .ip"#.to_string(),
        3001 => r#".message = parse_syslog!(.message)
.ip = parse_regex!(string!(.message), r'(?P<ip>\d+\.\d+\.\d+\.\d+)').ip
.user = parse_regex!(string!(.message), r'user[=:]"?(?P<user>[^\s"]+)').user
.class_uid = 3001
.category_uid = 3
.type_uid = 300101
.src_endpoint.ip = .ip
.dst_endpoint.ip = .ip"#.to_string(),
        5001 => r#".message = parse_syslog!(.message)
.ip = parse_regex!(string!(.message), r'(?P<ip>\d+\.\d+\.\d+\.\d+)').ip
.url = parse_regex!(string!(.message), r'(?P<url>https?://[^\s]+)').url
.method = parse_regex!(string!(.message), r'(?P<method>GET|POST|PUT|DELETE|HEAD)').method
.status = parse_regex!(string!(.message), r'(?P<status>\d{3})').status
.class_uid = 5001
.category_uid = 5
.type_uid = 500101
.src_endpoint.ip = .ip
.dst_endpoint.ip = .ip
.http.request.method = .method
.http.request.url = .url
.http.response.status_code = .status"#.to_string(),
        8001 => r#".message = parse_syslog!(.message)
.ip = parse_regex!(string!(.message), r'(?P<ip>\d+\.\d+\.\d+\.\d+)').ip
.file_name = parse_regex!(string!(.message), r'(?P<file>[\w\-. ]+\.(exe|dll|pdf|docx?|xlsx?))').file
.file_path = parse_regex!(string!(.message), r'(?P<path>[A-Za-z]:\\\\[^\s]+|/[^\s]+)').path
.class_uid = 8001
.category_uid = 8
.type_uid = 800101
.src_endpoint.ip = .ip
.file.name = .file_name
.file.path = .file_path"#.to_string(),
        _ => "".to_string(),
    }
}

fn shown_samples(samples: &[String]) -> String {
    samples.iter().take(5).enumerate().map(|(i, s)| format!("{}. {}", i+1, s)).collect::<Vec<_>>().join("\n")
}

fn infer_ocsf_path(source_field: &str) -> String {
    let field = source_field.to_ascii_lowercase();
    // Map common source field names to OCSF paths
    match field.as_str() {
        "srcip" | "src_ip" | "source_ip" | "saddr" | "src" => "src_endpoint.ip".to_string(),
        "dstip" | "dst_ip" | "destination_ip" | "daddr" | "dst" => "dst_endpoint.ip".to_string(),
        "srcport" | "src_port" | "source_port" | "sport" | "spt" => "src_endpoint.port".to_string(),
        "dstport" | "dst_port" | "destination_port" | "dport" | "dpt" => "dst_endpoint.port".to_string(),
        "proto" | "protocol" | "ipproto" => "connection_info.protocol_name".to_string(),
        "action" | "act" => "event.action".to_string(),
        "level" | "severity" | "severity_id" => "severity".to_string(),
        "devname" | "hostname" | "device" => "device.hostname".to_string(),
        "user" | "username" | "srcuser" | "ruser" => "actor.user.name".to_string(),
        "url" | "request" | "uri" | "requesturl" => "url.url_string".to_string(),
        "method" | "http_method" => "http.request.method".to_string(),
        "status" | "http_status" => "http.response.status_code".to_string(),
        "file" | "filename" | "file_name" => "file.name".to_string(),
        "path" | "filepath" | "file_path" => "file.path".to_string(),
        "message" | "msg" | "evt" => "message".to_string(),
        _ => "".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn heuristic_generates_valid_vrl() {
        let generator = VrlGenerator::heuristic();
        let profile = prism_profiler::SourceProfile {
            sample_count: 2,
            wire_format: "syslog-keyvalue".into(),
            wire_format_confidence: 0.95,
            decoder_chain: vec!["syslog".into(), "keyvalue".into()],
            source_family: "network-firewall".into(),
            source_family_confidence: 0.95,
            suggested_class_uid: Some(4001),
            source_hypotheses: vec![],
            extracted_field_names: vec!["srcip".into(), "dstip".into(), "action".into()],
            stable_detector_terms: vec!["devname=".into(), "type=traffic".into()],
            evidence: vec![],
            warnings: vec![],
            recommended_next_step: "".into(),
        };
        
        let vrl = generator.generate(&[
            "date=2024-01-01 time=12:00:00 devname=FW srcip=1.2.3.4 dstip=5.6.7.8 action=accept".into()
        ], &profile).await.unwrap();
        
        assert!(vrl.content.contains(".class_uid = 4001"));
        assert!(vrl.content.contains(".src_endpoint.ip"));
        assert!(!vrl.content.contains("```"));
    }

    #[test]
    fn test_compile_vrl_valid() {
        let vrl = r#"
.class_uid = 4001
.category_uid = 4
.type_uid = 400101
matched, err = parse_regex(string!(.message), r'(?i)srcip=(?P<val>[^\s,"]+)')
if err == null {
    .src_endpoint.ip = matched.val
}
.test_port = to_int("123") ?? null
"#;
        assert!(compile_vrl(vrl).is_ok());
        let res = run_dry_run(vrl, "no match here").unwrap();
        assert_eq!(res["class_uid"], 4001);
        assert_eq!(res["test_port"], 123);
        let res2 = run_dry_run(vrl, "srcip=1.2.3.4 foo=bar").unwrap();
        assert_eq!(res2["src_endpoint"]["ip"], "1.2.3.4");
    }

    #[test]
    fn test_compile_vrl_invalid() {
        assert!(compile_vrl("").is_err());
        assert!(compile_vrl("this is completely invalid vrl syntax %^&*").is_err());
    }

    #[test]
    fn test_run_dry_run_and_extract_fields() {
        let vrl = r#"
.class_uid = 4001
.category_uid = 4
.type_uid = 400101
.src_endpoint.ip = "10.0.0.1"
.dst_endpoint.ip = "8.8.8.8"
"#;
        let res = run_dry_run(vrl, "sample log line").unwrap();
        assert_eq!(res["class_uid"], 4001);
        assert_eq!(res["src_endpoint"]["ip"], "10.0.0.1");
        assert_eq!(res["dst_endpoint"]["ip"], "8.8.8.8");

        let fields = extract_fields(&res).unwrap();
        assert!(fields.contains(&"class_uid".to_string()));
        assert!(fields.contains(&"src_endpoint".to_string()));
        assert!(fields.contains(&"src_endpoint.ip".to_string()));
        assert!(fields.contains(&"dst_endpoint.ip".to_string()));
    }

    #[tokio::test]
    async fn test_validate_and_score() {
        let generator = VrlGenerator::heuristic();
        let profile = prism_profiler::SourceProfile {
            sample_count: 1,
            wire_format: "syslog-keyvalue".into(),
            wire_format_confidence: 0.95,
            decoder_chain: vec![],
            source_family: "network-firewall".into(),
            source_family_confidence: 0.95,
            suggested_class_uid: Some(4001),
            source_hypotheses: vec![],
            extracted_field_names: vec!["srcip".into(), "dstip".into()],
            stable_detector_terms: vec![],
            evidence: vec![],
            warnings: vec![],
            recommended_next_step: "".into(),
        };
        let sample = "date=2024-01-01 devname=FW srcip=1.2.3.4 dstip=5.6.7.8 action=accept".to_string();
        let script = generator.generate(std::slice::from_ref(&sample), &profile).await.unwrap();
        let report = generator.validate_and_score(&script.content, &[sample], &profile).await.unwrap();
        assert!(report.vrl_compile_passed);
        assert!(report.dry_run_passed);
        assert_eq!(report.fixtures_total, 1);
        assert_eq!(report.fixtures_passed, 1);
        assert!(report.overall_score > 0.0);
    }
}