[package]
name = "prism-common"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.23.1"
blake3 = { version = "1.8.7", features = ["serde"] }
bytes = { version = "1.12.1", features = ["serde"] }
chrono = { version = "0.4.45", features = ["serde"] }
hex = "0.4.3"
quinn = "0.11.12"
serde = { version = "1.0.229", features = ["derive"] }
