[package]
name = "prism-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
bytes = "1.12.1"
chrono = "0.4.45"
prism-common = { version = "0.1.0", path = "../prism-common" }
regex = "1.13.1"
reqwest = { version = "0.13.5", features = ["json"] }
serde = "1.0.229"
serde_json = "1.0.151"
tokio = "1.53.1"
vrl = "0.35.0"
