[package]
name = "prism-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3.34"
prism-common = { version = "0.1.0", path = "../prism-common" }
ratatui = "0.30.2"
serde = "1.0.229"
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
