name: CI

on:
  push:
    branches: [ "main", "master", "feat/**" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run Tests and Build Release
        run: cargo test --workspace && cargo build --release
